### ISSUE TITLE
Peer Evaluation || Milestone 2

### ISSUE THREAD

**Issue by aravindparappil46** [airavata-courses/MayDay#113]
Hi Team MayDay,
Went through your wiki and it gave me a really clear idea on what you guys are trying to achieve for the current milestone. Kudos!

Could you share the Jenkins credentials with me? You can email me at aparappi@iu.edu
@rojaraman @KalaRaja @arbansal 

EDIT 1:
After an initial review, here are my thoughts on the project so far:

- The UI looks really nice and clean. Great that you are following material design standards!
- Jenkins has been set up well too, with the master-worker configuration. The pipelines work as expected as well as the GitHub webhook
- Faced some small hiccups while trying to browse through the wiki doc because of its structure. All the necessary information was present but would recommend that a restructuring would help its readability. Also, could change the URLs into hyperlinks
- One line description for Jenkins jobs would be great
- Some minor CSS issues persist, like the text within recently searched cards overflow, user-profile icon has a click action but doesn't do anything
- 'Advanced Search' text can be kept outside of the actual card
- Can keep some text (app name?) / logo in the main login page. Looks empty with just the image now.

Overall, kudos for a great submission!! Looking forward to seeing how Sanjeevni progresses!

Issues raised are linked below:
#116 #119 #89 (noticed the issue but saw that it was already raised)  #123 #115

**Comment by KalaRaja** [comment]
@aravindparappil46 

jenkins credentials in mentioned under **Project instructions**  here in [Wiki](https://github.com/airavata-courses/MayDay/wiki/Milestone-2)

**Comment by aravindparappil46** [comment]
@KalaRaja Great! It did not catch my eye. Thanks. (Also, I think it's best if you take it out from the Wiki, considering this is a public repo)

**Comment by aravindparappil46** [comment]
My bad. Didn't notice that its a restricted account!

**Comment by KalaRaja** [comment]
@aravindparappil46 yes it's a restricted account , you can do everything on it except changing configuration, creating user, managing and creating credentials, managing nodes.

**Comment by aravindparappil46** [comment]
Thanks for the quick responses and prompt fixes, team! Going ahead and closing this issue.

Again, kudos on the great job!
