### ISSUE TITLE
Jenkins credentials not shared

### ISSUE THREAD

**Issue by kulsv** [airavata-courses/MayDay#114]
Hi Team, 
I dropped an email a few hours back about this.
Could you please share the credentials for Jenkins?
-
Shweta

**Comment by KalaRaja** [comment]
@kulsv 
 jenkins credentials in mentioned under **Project instructions** here in [Wiki](jenkins credentials in mentioned under Project instructions here in Wiki)

**Comment by kulsv** [comment]
Got it. Thanks.
