### ISSUE TITLE
Google Login Fails

### ISSUE THREAD

**Issue by aravindparappil46** [airavata-courses/MayDay#115]
When I tried to sign-in with Google, the following error popped up
![image](https://user-images.githubusercontent.com/43161107/53700900-51b24500-3dc5-11e9-8a7c-e30d75a7d006.png)

**Comment by KalaRaja** [comment]
@aravindparappil46 can you post the URL that you used for front end?

**Comment by aravindparappil46** [comment]
@KalaRaja http://149.165.168.167:4200/ 
Got it from the Wiki under _CI/CD using Jenkins (Master - slave configuration)._ section

**Comment by KalaRaja** [comment]
@aravindparappil46  use this one below, the IP that youre using is slave of  jenkins master.
Rhino front - end branch

Branch URL: https://github.com/airavata-courses/MayDay/tree/develop-client-rhino

Jenkins job: http://149.165.156.79:8080/job/rhino/

Test URL: **http://js-168-167.jetstream-cloud.org:4200/**

Pipeline Url: http://149.165.156.79:8080/job/deploy_pipeline/

**Comment by aravindparappil46** [comment]
Alright. Thanks for the prompt response!

**Comment by aravindparappil46** [comment]
Works now. Closing this.
