### ISSUE TITLE
Logging out on click of Icon on Navbar

### ISSUE THREAD

**Issue by aravindparappil46** [airavata-courses/MayDay#116]
After I log in successfully, if I click on the 'Sanjeevini' title on the navbar (top left), I am getting logged out
I guess it's not actually logging out, rather being redirected to home.
You can get rid of the hyperlink on that element. Easy fix!

**Comment by rojaraman** [comment]
@aravindparappil46  Fixed the issue. Please verify.

**Comment by aravindparappil46** [comment]
@rojaraman Yep. Looks good now! Closing this issue. Thanks!
