### ISSUE TITLE
'You also viewed' showing person I didn't view

### ISSUE THREAD

**Issue by aravindparappil46** [airavata-courses/MayDay#119]
I searched for a doctor ("Wayne") but in the 'You also viewed' section, I'm able to see a 'Mark' as well as a blank card
Also, not sure what the number on top of each card denotes
![image](https://user-images.githubusercontent.com/43161107/53701118-d4d49a80-3dc7-11e9-90b1-678440bb73e7.png)

**Comment by aravindparappil46** [comment]
Ok. I refreshed my page now, hoping that it's a late loading issue and I got some other cards
![image](https://user-images.githubusercontent.com/43161107/53701135-08172980-3dc8-11e9-8be5-0a43501bc47d.png)

Is it because all the searches done by any user is shown here?

**Comment by rojaraman** [comment]
Hi Aravind, 
The result is supposed to be user specific. I believe userid is not being passed to the service for some reason. We will look into it.
Thank you,
Roja

**Comment by rojaraman** [comment]
@aravindparappil46  fixed this issue. Please verify.

![issue](https://user-images.githubusercontent.com/7594406/53704686-f005d100-3dec-11e9-9b3f-2e64b70a5f85.JPG)

**Comment by aravindparappil46** [comment]
@rojaraman Yep. Works now! Closing this issue.
