### ISSUE TITLE
Not able to login to the application after building

### ISSUE THREAD

**Issue by kulsv** [airavata-courses/MayDay#120]
Hi Team,

I tested the entire application first and then tried to test the jenkins deployment.
All the jobs on Jenkins were triggered and were successful right after adding dummy commits to the develop branches. Hence working perfectly!
I tried logging in and testing after every dummy build. However, After building the red job (profile management), I am not able to login to the system. No error messages are provided.

-
Shweta

**Comment by aravindparappil46** [comment]
This is interesting. 
I also performed a dummy commit to red (develop-microservice-red) and after the Jenkins jobs finished successfully, I am able to log in.

Must have been a one time thing, perhaps.

**Comment by kulsv** [comment]
I tried 4 times. Tried to sign up as well. No luck yet.
Initially I thought that MySQL is getting refreshed after every build so it's not able to figure out my credentials. Thus I tried to create another pair of credentials. I was able to login then. Again after a while when I built the next job, I was unable to login with the previous credentials and not able to create new credentials too.

**Comment by aravindparappil46** [comment]
Ah. Did you try the Google OAuth one? 
Also, I do not think they are using MySQL anymore as they seem to have migrated to H2 Distributed DBs.

**Comment by kulsv** [comment]
Ah sorry! I tend to mention MySQL as I'm using that in my project. Comment is edited. Thanks for noticing that.
And yeah, I tried OAuth. It's not working too. But I think it's mentioned in their document that as of now, the manual signup/sign in is working. So I didn't pay attention to OAuth.

**Comment by KalaRaja** [comment]
Guys, this is a known issue, We are working on it, this would end up in next milestone. The thing is, h2 database cleans whenever the application is re deployed.

I will update the wiki.

Note: Oauth works nonetheless. Only the manual signup login has this bug.

**Comment by aravindparappil46** [comment]
@KalaRaja Got it. Thanks for the update

**Comment by KalaRaja** [comment]
Oauth works, please make sure you are using the correct URL, visit this issue #115

**Comment by kulsv** [comment]
Thanks @KalaRaja for letting me know. Seems, I was testing OAuth on the wrong URL. OAuth is working fine now. CLosing this issue.
