### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by kulsv** [airavata-courses/MayDay#121]
Hi Team,
Overall, the UI looks decent. However, I faced following issues:

1. In the results for the doctors, the very first result on my screen is half hidden to the left and I am not able to scroll it to view.
2. links for about contact and the dot beside my username not working.
3.  Pagination shows page indexes from -2, -1, 0, 1, 2, 3 where current result is loaded on page 1.
4. At the bottom, it is showing the strings I never searched for.

Also, following are the suggestions that I'd like to share with you (completely optional):
1. UI suggestion - display more results on each page as user can see only 4-5 results per page and I get 900 pages long results. User cant keep visiting all the 900 pages. Or you could display first 10 pages and give an option of "Load More"
2. At the bottom - top search strings - maybe on click of them you could show the same result again. that'd be helpful for the user
3. after login, on click of Sanjeevni, it takes me back to sign up page where as ideally, it should take me to home page.

Thanks,
Shweta

**Comment by KalaRaja** [comment]
@kulsv thank you for your valuable feedback.
we are working on layout and pagination issues, will delegate these issues for next milestone.

optional features make so much sense, we will surely implement these.

**Comment by kulsv** [comment]
Are you planning to create new issues for the points I mentioned above? I'll close this issue if you plan to do so.

**Comment by rojaraman** [comment]
@kulsv yes we will create issues for the issues which are not fixed yet.

Fixed Point 4 - At the bottom, it is showing the strings I never searched for.
Fixed Point 3 - after login, on click of Sanjeevni, it takes me back to sign up page where as ideally, it should take me to home page

Result of the issues will be handled in next milestone.
