### ISSUE TITLE
[KUBERNETES] setup kube master and worker nodes

### ISSUE THREAD

**Issue by KalaRaja** [airavata-courses/MayDay#130]
one tutorial here https://www.edureka.co/blog/install-kubernetes-on-ubuntu

**install on centos machine**

**Comment by KalaRaja** [comment]
script branch : kuber_docker_scripts

#### master node
`149.165.157.53`

#### dashboard
https://149.165.157.53:32357/#!/overview?namespace=default

#### worker nodes
* 149.165.156.154
* 149.165.157.15
* 149.165.157.198


![Capture](https://user-images.githubusercontent.com/42894144/54833291-320b8f80-4c94-11e9-9a35-05013e76fcbb.PNG)

**Comment by rojaraman** [comment]
Kubernetes Setup : 
Master : 149.165.156.182
Slave Node 1 : 149.165.156.154
Slave Node 2 : 149.165.170.204
Slave Node 3 : 149.165.157.15
