### ISSUE TITLE
Review for Assignment 2

### ISSUE THREAD

**Issue by nawazkh** [airavata-courses/MayDay#132]
Hey Team,
I was about to start the review for assignment2.
Please share your Jenkins credentials with me on Slack.

**Comment by nawazkh** [comment]
Hey Team, 
Red System is facing some issue with the build. Please guide me here.

**Comment by arbansal** [comment]
Hi Nawaz,

We had made some changes to the scripts in Jenkins to implement docker and kubernetes. Have reverted these now, can you please try again?

**Comment by nawazkh** [comment]
Hey team,
I just completed reviewing your project.

I have few suggestions:
1. Please do include test cases to test the functionality of major services at the build time. 
2. Please shift away from the H2 DB, it is not recommended for the final version of the system.

And In your presentations, I highly recommend you to stress on the challenges you faced and the design decisions you had to take to overcome them. If-presented-well, It should fetch you extra points.
I can see that a lot of hard work was put in the project. UI is amazing and search functionality is great!

Keep up the great work!

Best,
Nawaz
