### ISSUE TITLE
Peer Evaluation | Milestone 3

### ISSUE THREAD

**Issue by aravindparappil46** [airavata-courses/MayDay#140]
Hi Team,
Creating this issue to keep track of my comments for Milestone 3

**Comment by aravindparappil46** [comment]
Hi,
I tried logging in to the dashboard but could not see any Pods or services up.
![image](https://user-images.githubusercontent.com/43161107/55512386-004ddd80-5631-11e9-853e-772c107827a8.png)

**Comment by KalaRaja** [comment]
@aravindparappil46 we have changed the services from load balancer to node port, jenkins is redeploying everything , sorry for inconvenience,

**Comment by aravindparappil46** [comment]
No worries. Will wait a while for Jenkins to finish

**Comment by KalaRaja** [comment]
everything is working fine now

**Comment by aravindparappil46** [comment]
Able to access the app now. Everything works great!

Here are some minor cosmetic changes that caught my eye immediately:
1. Log in page looks beautiful. However, you could add a logo/title at this page (A header that says Sanjeevini, perhaps?)
2. For doctors who do not have practices, the pink button (No Practices) could be changed to gray instead 
3. Here's a corner case bug for the pagination:
![image](https://user-images.githubusercontent.com/43161107/55516494-59227380-563b-11e9-8ab2-716f3b90f8fb.png)
Say, I enter 9925 in the box (whereas there are only 9924 pages in total), the doctors panel moves up and the UI messes up

**Comment by aravindparappil46** [comment]
As far as the milestone is concerned, have tested the features and everything looks great
- Made a dummy commit and Jenkins trigger works as expected
- Tried killing pods from the dashboard and the app remains fault tolerant 

The map view for doctors is a nice add-on and adds to the appeal of the UI! Good job!

Also noticed that you guys migrated to PostgreSQL in this milestone. Doing this at this stage must have been quite a hiccup! Kudos on integrating it with everything and making it work!

The pagination bug in my comment above is a very niche/corner case which I stumbled upon and shouldn't take up much priority in your backlog items. It doesn't seem critical.

Overall, I can notice the effort put into this milestone with regard to the thought given to Jenkins jobs and Kubernetes, along with enhancing the app itself. Great work pulling through!
