### ISSUE TITLE
Peer Review for Milestone 3

### ISSUE THREAD

**Issue by Praneta-Paithankar** [airavata-courses/MayDay#141]
Hello Team,

I've started to review your application for this milestone. I am facing two issues right now. It would be great if you could resolve it. 
Issues are 
1. I cannot sign up on the webpage.
2. Also, I found that blue microservice is not running.

Regards,
Praneta

**Comment by Praneta-Paithankar** [comment]
Logs in k8s dashboard shows that it does not have 'connect' module present

**Comment by rojaraman** [comment]
Fixed the issue. Can you please try again now.

**Comment by Praneta-Paithankar** [comment]
@rojaraman Login is working now. Thanks

**Comment by Praneta-Paithankar** [comment]
It does not show external endpoints for services
<img width="1440" alt="Screen Shot 2019-04-03 at 3 14 32 PM" src="https://user-images.githubusercontent.com/24793322/55511252-1c03b480-562e-11e9-95a8-ffadc229ab4b.png">

**Comment by Praneta-Paithankar** [comment]
Dashboard doesn't show external endpoints for services. Could you check that also?
<img width="1440" alt="Screen Shot 2019-04-03 at 4 32 26 PM" src="https://user-images.githubusercontent.com/24793322/55511299-405f9100-562e-11e9-836e-374f10d7bf60.png">

**Comment by KalaRaja** [comment]
The services are running fine, we have not attched load balancer ip to the services so kube master allocated ephemeral ip to them.
I have changed the type from load balancer to node port, now it should show as running status. External endpoint are not shown by kubectl in case of NodePort type service.

https://github.com/airavata-courses/MayDay/commit/d3b0af767fb32c366dbc802ec755f44782129696
https://github.com/airavata-courses/MayDay/commit/df837705c60aaaebdce04cd0585f6a281fcda300
https://github.com/airavata-courses/MayDay/commit/459d238e03db6adc3891d465f0e8de992925b01e
https://github.com/airavata-courses/MayDay/commit/46e7167c89f255a6b267259124b9522a9041b88a

**Comment by Praneta-Paithankar** [comment]
Hello Team,

I was able to test the application using frontend and verify the k8s deployment. Wiki is comprehensive enough to understand the tasks achieved and how to validate the tasks. The front end is user-friendly.

I do have a few suggestions:
1. It will be easy to understand if you remove drug name in the search bar as it's not the part of the search functionality.
<img width="490" alt="Screen Shot 2019-04-03 at 5 49 26 PM" src="https://user-images.githubusercontent.com/24793322/55515668-19f32300-5639-11e9-81f5-4a509e00543f.png">

2. Also In recently searched terms section, you can combine terms by ignoring their cases.
e.g. Cold and cold
<img width="340" alt="Screen Shot 2019-04-03 at 5 49 10 PM" src="https://user-images.githubusercontent.com/24793322/55515675-1f506d80-5639-11e9-94f2-657577a3be33.png">

3. You can also remove not available practitioners from the search result to make it more effective.
<img width="572" alt="Screen Shot 2019-04-03 at 5 50 40 PM" src="https://user-images.githubusercontent.com/24793322/55515681-22e3f480-5639-11e9-997c-565ec1b423fe.png">

For me, advanced search options weren't working.

Overall Good work guys! Thank you for answering all my queries.

Good luck!! 

Praneta

**Comment by KalaRaja** [comment]
@Praneta-Paithankar thank you for valuable comments. We will remove drug search and also advanced search is not yet supported, will support it.
