### ISSUE TITLE
Error : Red Microservice end point  throwing an error.  (Milestone 1)

### ISSUE THREAD

**Issue by Praneta-Paithankar** [airavata-courses/MayDay#40]
Hello ,

I followed the steps given in a wiki to install red microservice. I am getting 404 error while accessing the endpoint on browser. Also in wiki it shows 2 url for red microservice. Can you tell me which one is correct?  localhost:8080/rest/test  and  localhost:3000/test
![screenshot from 2019-02-06 20-20-30](https://user-images.githubusercontent.com/24793322/52385030-f4d5a000-2a4d-11e9-810f-780f87f00fce.png)

**Comment by KalaRaja** [comment]
can you provide terminal logs please

**Comment by arbansal** [comment]
Can you please try this updated url: http://localhost:8080/rest/customers/test for testing Red. We have updated the Wiki as well.

**Comment by Praneta-Paithankar** [comment]
I will try

**Comment by KalaRaja** [comment]
@arbansal please attach a screenshot of /test returning 200 OK

**Comment by arbansal** [comment]
![image](https://user-images.githubusercontent.com/42485641/52536759-ba5d5300-2d2c-11e9-870f-8655b570251a.png)
