### ISSUE TITLE
Error : Blue Microservice is not working

### ISSUE THREAD

**Issue by Praneta-Paithankar** [airavata-courses/MayDay#43]
Hello,

I am running blue microservice . it shows an error while accessing the endpoint.

![blue](https://user-images.githubusercontent.com/24793322/52385775-1dab6480-2a51-11e9-927b-c48fa3e0dc9d.png)

**Comment by rojaraman** [comment]
Please switch to Raw data on your browser as /test will output 200 OK as text on the browser and 200 OK response status in the header.

**Comment by Praneta-Paithankar** [comment]
Thanks. It's working. I am closing this issue.
