### ISSUE TITLE
Functionality: Search Doctors by Name not Working

### ISSUE THREAD

**Issue by deepakh2810** [airavata-courses/MayDay#45]
In the wiki page it is mentioned that Search Doctors by Name Working, but it isn't.

**Comment by KalaRaja** [comment]
@deepakh2810 please take latest pull from develop-client-rhino and verify now, we have added search functionality.

**Comment by arbansal** [comment]
linking #47

**Comment by deepakh2810** [comment]
Looks good! @KalaRaja 
Great Job!
