### ISSUE TITLE
Click on "Sanjeevni" Log's you out of the Portal.

### ISSUE THREAD

**Issue by deepakh2810** [airavata-courses/MayDay#46]
Renaming it to Log out or include document that if the user clicks there it would log out, can help.

**Comment by rojaraman** [comment]
This was intentional as we have not implemented logout feature.

**Comment by KalaRaja** [comment]
now we have proper logout button like this

![image](https://user-images.githubusercontent.com/42894144/52535892-d7d8ef80-2d21-11e9-8e84-b1ea26a0f54d.png)

[d61857f4179064b6e4a350121029a2b4b6b33c04](https://github.com/airavata-courses/MayDay/tree/d61857f4179064b6e4a350121029a2b4b6b33c04)

**Comment by deepakh2810** [comment]
@KalaRaja 
This looks perfect, since as a user now we know where to go ahead and log out!
