### ISSUE TITLE
Search doctors by name Not Working.

### ISSUE THREAD

**Issue by deepakh2810** [airavata-courses/MayDay#47]
Search doctors by name Not Working.

**Comment by deepakh2810** [comment]
See Doctors nearby, See recent searches, See frequent searches, Search practices -> wiki says these are working , but not working.

**Comment by rojaraman** [comment]
@deepakh2810 
This was left out in another branch. Merged the changes to develop-client-rhino. Please pull the changes and verify again.

Frequent searched, Search practices are not implemented and hence not mentioned in the wiki as completed.
You can search any keyword and it will be displayed in Recent search section on click of "view more"

Thanks,
Roja

**Comment by deepakh2810** [comment]
@rojaraman 
Seems to be an issue with the WIKI at the time i tested the same. After changes in the WIKI with your latest commit, it makes sense.

Thanks,
Deepak Hanumanthaiah

**Comment by KalaRaja** [comment]
pull from develop-client-rhino and please check now

**Comment by KalaRaja** [comment]
searching doctors by name is now working.
![image](https://user-images.githubusercontent.com/42894144/52535813-ebd02180-2d20-11e9-8fba-959905c23ef7.png)

[bceeb03db5d8825a1957c3652593849ff0033d93](https://github.com/airavata-courses/MayDay/tree/bceeb03db5d8825a1957c3652593849ff0033d93)
