### ISSUE TITLE
Peer review Milestone1 

### ISSUE THREAD

**Issue by Praneta-Paithankar** [airavata-courses/MayDay#49]
Hello guys,

I am trying to reproduce all the functionality mentioned in the wiki for this milestone. I am able to login in using google and view doctors nearby on the home screen. I like the UI.
Following functionalities are not working for me:

1. The user can search for doctors using the name. - The result will be displayed in console and search result page is targetted for milestone 2
--- I can see data which is fetched by nearby. I don't see any new data added after clicking on the search.
![doctorsearcherror](https://user-images.githubusercontent.com/24793322/52389816-5f450b00-2a63-11e9-8b0a-b44573e484a4.png)
2. On click of "View more", the user can see a list of keywords searched previously. 
-- After clicking on view more, I am getting an error. I have attached the screenshot of the same.
![viewmore](https://user-images.githubusercontent.com/24793322/52389920-db3f5300-2a63-11e9-9ec6-bea5fe1f352e.png)

3. Clicking on the user name logs out of the website. 

Nice to have:

1. Please make sure that Wiki is consistent. e.g. There are some functionalities given in proposed functionality is not working such as search practices. There are 2 URLs are mentioned for the same microservice (Red).
2. It would be really easy if you could provide URL of UI.
3. All packages that you have installed for python, you could specify in the requirements.txt file. For this, you can use pip freeze command.
4. For showing nearby doctors, it would be great if you could show location(area).

**Comment by KalaRaja** [comment]
thanks for valuable comments @Praneta-Paithankar, I am gld you liked the UI. 
The search doctors by name functionality is in place , please pull from rhino and verify.
We are working on other comments of yours.

**Comment by KalaRaja** [comment]
Hi Praneta, all review comments are taken into account.

1. The search by name has been imolemented, check out #47 
2. Requirements.txt has been put into milestone 2 bucket.
3. Separate logout button is in place now , checkout #46 
4. Wiki is now consistent.
5. Nearby doctors feature now shows location.
![image](https://user-images.githubusercontent.com/42894144/52536009-53876c00-2d23-11e9-87b4-a0f07cf41c9a.png)

[fe59e3497fbf06cf4245bcc264c2db45f8fb0bf2](https://github.com/airavata-courses/MayDay/tree/fe59e3497fbf06cf4245bcc264c2db45f8fb0bf2)
