### ISSUE TITLE
unable to load virtual env using given instructions

### ISSUE THREAD

**Issue by varun-mach** [airavata-courses/MayDay#51]
Please let me know how to proceed further with the virtual env installation. As per current instructions on wiki, I'm getting virtualenv command not found on executing: virtualenv venv

**Comment by rojaraman** [comment]
Please check if you installed virtualenv using pip install virtualenv.
Then try running virtualenv venv.

Thanks,
Roja

**Comment by varun-mach** [comment]
I did install. Still getting error virtualenv command not found

**Comment by rojaraman** [comment]
We are not very sure about why it is not working on your system.
Please try this using  "pip install virtualenv --user"
Alternatively,
Will it be possible for you to try a few solutions from the link below as we cannot reproduce it in our laptops.

https://stackoverflow.com/questions/31133050/virtualenv-command-not-found

Thanks,
Roja

**Comment by varun-mach** [comment]
None of those worked. Had to do a python -m virtualenv env to get it to work
