### ISSUE TITLE
Unable to tell if python server has started or not

### ISSUE THREAD

**Issue by varun-mach** [airavata-courses/MayDay#53]
Please put in some logs during server startup which will help to know if the server has started successfully or not.

**Comment by rojaraman** [comment]
Hi Varun,

Please refer the attached screenshots. This is how we are notifying if the service is up or not.

Thanks,
Roja

![bluestart](https://user-images.githubusercontent.com/7594406/52524432-ea442200-2c6a-11e9-9be1-6ed4325a98a5.JPG)
![test](https://user-images.githubusercontent.com/7594406/52524433-ea442200-2c6a-11e9-89b5-ae93f9a73509.JPG)

**Comment by varun-mach** [comment]
![image](https://user-images.githubusercontent.com/8275960/52524624-efa26c00-2c6c-11e9-8d7a-2ee2cf7350d6.png)
 Im not getting any message after startup

**Comment by rojaraman** [comment]
We will look into it and update you.

Thanks,
Roja

**Comment by KalaRaja** [comment]
Varun, can you hit this url in your browser
localhost:8000/test,
 it's written in the wiki
